on:
  - push
  - pull_request
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.31
      - run: bun ci
