on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # 毎日12時に実行 (JST)
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.5
      - run: bun install --production
      - run: bun start
    env:
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
